# Generated by Django 5.2.8 on 2025-12-08 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryptapp', '0002_filerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('encrypt', 'Encrypt'), ('decrypt', 'Decrypt')], max_length=10)),
                ('carrier_filename', models.CharField(blank=True, max_length=255)),
                ('stego_filename', models.CharField(blank=True, max_length=255)),
                ('files_info', models.JSONField(default=list)),
                ('payload_size', models.BigIntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
