# Generated by Django 5.2.8 on 2025-12-08 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encryptapp', '0003_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileRecord',
        ),
    ]
